### ISSUE TITLE
SEP-10: use configured SEP-31 public key if specified

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-anchor-tests#88]
### What problem does your feature solve?

SEP-31 has a configuration option to specify the public use, but the SEP-12 tests don't use this key. For anchors that require the SEP-12 account to match a list of known public keys, these tests will fail.

### What would you like to see?

Update the SEP-12 tests to use the configured public key if it is specified.

**Comment by reecexlm** [comment]
updated description as the issue reported is about the ability to specify the secret key for sep-12 not sep-10.
