### ISSUE TITLE
sep12 "can retrieve customer using SEP-10 token" doesn't take in account the "account" field from the config

### ISSUE THREAD

**Issue by CrisanP13** [stellar/stellar-anchor-tests#97]
### What version are you using?

stellar anchor tests version 0.1.0

### What did you do?

run the sep 12 tests through the cli using the following config:
```json
{
    "12": {
        "customers": {
            "toBeCreated": {
                "account": "GDZJYGQJFAA6WGTAR43XT3U4STY3CPRTEMPUFD74HAQYUAQ62SLEQ2UH",
                "first_name": "John",
                "last_name": "Doe",
                "email_address": "joe@email.com",
                "address_country_code": "DEU",
                "city": "munchen",
                "state_or_province": "bavaria",
                "address": "street address nr. 2",
                "postal_code": "56709",
                "type": "sep-12-person"
            },
            "sendingClient": {
                "account": "GBYTY7SB6BVG2EGS3GYFHAY4RURGB6ARSKAFQXUPTKQ7DJN5XEXIONQE",
                "first_name": "Tomer",
                "last_name": "Weller",
                "email_address": "tomer@stellar.org",
                "type": "sep-12-person",
                "address_country_code": "DEU",
                "city": "munchen",
                "state_or_province": "bavaria",
                "address": "street address nr. 2",
                "postal_code": "56709"
            },
            "receivingClient": {
                "account": "GBYTY7SB6BVG2EGS3GYFHAY4RURGB6ARSKAFQXUPTKQ7DJN5XEXIONQE",
                "first_name": "Lydia",
                "last_name": "Wagner",
                "email_address": "lydia@stellar.org",
                "type": "sep-12-person",
                "address_country_code": "DEU",
                "city": "munchen",
                "state_or_province": "bavaria",
                "address": "street address nr. 2",
                "postal_code": "56709"
            },
            "toBeDeleted": {
                "first_name": "Jane",
                "last_name": "Doe",
                "email_address": "jane@email.com",
                "type": "sep-12-person"
            }
        },
        "createCustomer": "toBeCreated",
        "deleteCustomer": "toBeDeleted",
        "sameAccountDifferentMemos": [
            "sendingClient",
            "receivingClient"
        ]
    },
    "31": {
        "sendingAnchorClientSecret": "SCIWS2OQIHUY5H3ICQX57IONHONK2WDJS64JDZ7WHT6JO7LQP2IWZ2EE",
        "sendingClientName": "sendingClient",
        "receivingClientName": "receivingClient",
        "transactionFields": {
            "accountID": "b0a7138d-2a13-4cdb-b8d1-0b5643153858",
            "account_name": "alensky alen virtual",
            "bank_routing_number": "1264598421",
            "account_number": "2859268459",
            "bank_account_type": "Savings"
        }
    }
}
```

### What did you expect to see?
Expected the "can retrieve customer using SEP-10 token" test to pass and the token used to contain the the account associated with the "toBeCreated" customer.

### What did you see instead?
Test failed. After debugging saw that the token used for the get call contains the wallet associated with the "sendingAnchorClientSecret" instead. Put a breakpoint before the 'getCustomerCall' creation in  '@stellar\anchor-tests\src\tests\sep12\getCustomer.ts' in the 'canFetchExistingCustomerBySep10Token' test.
![image](https://user-images.githubusercontent.com/14197950/193794323-eea5db11-7475-4e78-9996-8ccf20252554.png)

**Comment by CrisanP13** [comment]
@stfung77 i would expect the account specified by the `sendingClient` to be used for the get request instead of the one specified by the `sendingAnchorClientSecret`. the obvious problem is that it's impossible to to get the secret key so that you can sign the transaction but it doesn't make sense as it is now either since if i would be able to retrieve the client created by the secret key then what happens if there are more than one of them? not sure if it work to be able to specify in the config the secret key for the clients to be created as well
my use case is that one our customers onboard their clients so we have a configuration for a customer that associated their account ( which would be `sendingAnchorClientSecret`) which they use to authenticate and then they create sep-12 customers through our anchor which is associated with their clients account ( which would be the `sendingClient` account field)

**Comment by CrisanP13** [comment]
Then it seems strange that the account and memo fields are forwarded from the config to the call. Since they are deprecated i would expect to get a warning or an error for the config.

**Comment by CrisanP13** [comment]
@stfung77 thank you for the help. the problem seems to be how to maintain the current version and the old one. Might be an idea to create a new test for the deprecated behavior since there are still anchor that support it.
Is there any timing for how long the deprecated behavior will be present in the docs, as in are there plans to remove it completely in the future?

**Comment by JakeUrban** [comment]
We don't have any plans to remove it, the deprecation is more to inform the reader that there is a preferred alternative.

But even if you do use `account`, it must match the `sub` value of the JWT token issued in SEP-10.
